[[redirects]]
  from = "http://sydneybackflowplumbing.com.au/*"
  to = "https://sydneybackflowplumbing.com.au/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.sydneybackflowplumbing.com.au/*"
  to = "https://sydneybackflowplumbing.com.au/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.sydneybackflowplumbing.com.au/*"
  to = "https://sydneybackflowplumbing.com.au/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
